### ISSUE TITLE
Help with the intrepretation

### ISSUE THREAD

**Issue by Mussa1122** [alexyermanos/Platypus#16]
Hi

Indeed, this is not a problem with your software rather I need help

![Rplot53](https://user-images.githubusercontent.com/68249398/169863974-659c056e-95a9-4747-96d6-b1936c74589e.png)

For instance, in the above plot, do these are novel or already known? How I can find their targets?

Thanks for any intuition and help

**Comment by alexyermanos** [comment]
Hello - this really depends on the dataset unfortunately. Screening for T cell receptor specificity is quite challenging (e.g. https://www.biorxiv.org/content/10.1101/2020.06.23.166363v1) and there are some databases, but these are often quite incomplete (https://vdjdb.cdr3.net/)
