### ISSUE TITLE
Does not detect `sample_filtered_feature_bc_matrix` GEX output from `multi`

### ISSUE THREAD

**Issue by aseyedia** [alexyermanos/Platypus#19]
https://github.com/alexyermanos/Platypus/blob/75aceffd2cf54a48bd2513fdc083c01894cdea46/R/VDJ_GEX_matrix.R#L1296-L1312

Hi,

I am trying to load VDJ-B, VDJ-T and GEX outputs from Cell Ranger `multi` with `VDJ_GEX_matrix()` and it appears that perhaps Cell Ranger 7 has updated the output directory names, because `VDJ_GEX_matrix()` aimed at `multi` output's `outs` directory produces the following error:

```
The GEX directory filtered_feature_bc_matrix or sample_feature_bc_matrix was not found at the given path. Please revise GEX input pathsDone with GEX pipeline 
```

However, the relevant directory is named `sample_filtered_feature_bc_matrix`. 

Setting the `h5` to `sample_filtered_feature_bc_matrix` using `GEX.read.h5` works.

**Comment by vickreiner** [comment]
Hi!
Thanks for letting us know! 
We always try to keep up with the Cellranger's innovations in folder naming. I will add the `sample_filtered_feature_bc_matrix` to the path-completion options.

**Comment by vickreiner** [comment]
Update pushed to the Platypus/R folder. Will be integrated in the next build
Thanks again!
