### ISSUE TITLE
VDJ_available not found in all samples

### ISSUE THREAD

**Issue by Andy-ChanKP** [alexyermanos/Platypus#24]
Hi again! 

Sorry for opening another ticket again - I am wondering why VDJ is not found in the Seurat object for sample 7-9? Even though clearly B cell clusters are present in these samples. Must be something with the VDJ_GEX_matrix function, or my Seurat.in object. 
Any speculations as to how this error happens would be very welcome and appreciated. 

Many thanks, 
Andy
![image](https://user-images.githubusercontent.com/72179109/187367971-0b85f414-cfe0-4e7b-a734-e92e8fff39b0.png)

<img width="616" alt="image" src="https://user-images.githubusercontent.com/72179109/187368840-fc50ca33-9080-439c-ac35-2f62349b4f34.png">
<img width="415" alt="image" src="https://user-images.githubusercontent.com/72179109/187368882-1d2b5fca-a3c0-4bf7-b665-b938d174b6c5.png">
<img width="343" alt="image" src="https://user-images.githubusercontent.com/72179109/187368922-b75bad38-a4c4-4f1a-82a3-89c5b7e50e24.png">

**Comment by vickreiner** [comment]
Hi Andy,

can you check for me if the VDJ for samples 7-9 are present in vgm_without_13F_LN
`table(vgm_without_13F_LN[[1]]$sample_id`)
and, to see if the integration worked from the side of VDJ: 
`vgm_without_13F_LN[[1]] %>% group_by(sample_id) %>% summarise(sum(GEX_available))`

Thanks a lot!

**Comment by Andy-ChanKP** [comment]
Thank you for your prompt reply... 
Very interesting... So they are present, but the integration did not work. 

<img width="481" alt="image" src="https://user-images.githubusercontent.com/72179109/187386165-c43fa336-f38d-431a-8be0-5c1ac559bb51.png">

**Comment by alexyermanos** [comment]
Could you manually check the overlap for s7 GEX and s7 VDJ barcodes in VGM[[2]] and VGM[[1]] respectively and compare this to one that worked (e.g. s6 GEX and s6 VDJ ? e.g. using something like length(intersect())

**Comment by vickreiner** [comment]
Hi!
I just pushed a new version of the VGM which, if verbose = TRUE, prints a pairwise intersect table of all GEX vs. all VDJ. That should highlight any mismatches or wrong orders. 
Could you try this? 
Thanks!

**Comment by Andy-ChanKP** [comment]
Hi Victor and Alex, 

Here is the pairwise intersect table... there are certainly many mismatches... 

How do I fix this? 

Many thanks, 
Andy

<img width="143" alt="image" src="https://user-images.githubusercontent.com/72179109/187395208-818b0e65-4d7c-4562-9a2d-fdffbf549f8c.png">
<img width="135" alt="image" src="https://user-images.githubusercontent.com/72179109/187395268-73b21189-fd55-4641-9183-2b396966ba48.png">
<img width="130" alt="image" src="https://user-images.githubusercontent.com/72179109/187395333-899abc9d-dd69-4a7a-a59c-004817d6befb.png">
<img width="131" alt="image" src="https://user-images.githubusercontent.com/72179109/187395395-f42f1a21-ed98-4163-8a07-ec4c132fb08e.png">
<img width="130" alt="image" src="https://user-images.githubusercontent.com/72179109/187395452-c63bafd2-0395-4308-b71f-b7390462b53c.png">
<img width="128" alt="image" src="https://user-images.githubusercontent.com/72179109/187395498-bb55821f-d79e-4065-8506-1a3df0b32fe6.png">

**Comment by vickreiner** [comment]
Some low levels of overlap between raw barcodes and samples is to be expected. 
From experience the numbers in this table are a bit higher than what I would expect.

Apart from that, there are large overlaps between several samples which (without knowing the experiment design behind it) seem out of place. 

To me it looks like:
1. GEX s9 would pair with VDJ s7
2. GEX s8 would pair with VDJ s9
3. There is an overlap of GEX s7 and s4; VDJ s4 pairs up with both GEX s7 and s4, while VDJ s7 pairs with s9 (1.) 

Not really sure what happened here. 
For the future I will keep this VDJ_GEX_matrix overlap table in, so that users are made aware of possible mismatches

**Comment by Andy-ChanKP** [comment]
Hi Victor, 

I think your interpretation is accurate - when I do exchange VDJ s7 and s9 with their "correct" GEX counterparts of s9 and s8 respectively, those B cell clusters of s8 and s9 light up. Not too sure why their GEX and VDJ paths are not the same in the first place. Human error mixing them up? 

That leaves us s7, and mixing up with s4 and others in different ways. 

I will discuss this with our lab members (@mbart13) and also the core facility, and will let you know how we think it could have happened in the first place. It is so baffling... 

Really appreciated your help throughout!! You guys really helped me a lot. 

Many thanks, 
Andy

**Comment by vickreiner** [comment]
Always happy to help! 
Hope you can figure out what happened to these samples.
