### ISSUE TITLE
how to integrate the seurat analysis GEX results to Platypus

### ISSUE THREAD

**Issue by songeric1107** [alexyermanos/Platypus#26]
Is there a way to integrate the GEX seurat object to Platypus without starting the analysis from the beginning?

**Comment by vickreiner** [comment]
Hi! 
Yes, to the parameter _Seurat.in_ you can provide your existing processed Seurat object. 
For correct integration the metadata of this object must contain a group_id column (1 - n) and a sample_id column formatted as _s1, s2..._ in the same order as VDJ paths.

Hope that helps! Let me know if any questions come up!
