### ISSUE TITLE
Errors running antibody forests vignette 

### ISSUE THREAD

**Issue by duinsel** [alexyermanos/Platypus#27]
Hi,

I tried running the antibody forests vignette on several systems. With the CRAN version of Platypus, the datasets load OK, but all subsequent analysis with the AntibodyForests function throws an error

`AntibodyForests(VGM[[1]],
                network.algorithm = 'tree',
                specific.networks = 'clonotype7') %>% AntibodyForests_plot(node.label = NULL, node.scale.factor = 8)
Error in assign(mname, def, where) : 
  cannot add bindings to a locked environment`

I saw this on several systems (Win/linux), including a fresh install.

I performed a Github install of Platypus instead. Fortunately, I can generate the plots on VDJ data in this way, but that install generates another error when loading the GEX data

`PlatypusDB_fetch(PlatypusDB.links = c("agrafiotis2021a/TNFR2.BM.3m.S1/ALL"), 
                                     load.to.enviroment = T, combine.objects = T)
2022-10-02 09:32:03: Starting download of agrafiotis2021a_TNFR2.BM.3m.S1_VDJ.RData...
2022-10-02 09:32:04: Starting download of agrafiotis2021a_TNFR2.BM.3m.S1_GEX.RData...
[1] "agrafiotis2021a_TNFR2.BM.3m.S1_VDJGEXdata"
> VGM <- VDJ_GEX_matrix(Data.in = list(agrafiotis2021a_TNFR2.BM.3m.S1_VDJGEXdata), parallel.processing = "parlapply", trim.and.align = T) 
09:32:29 
 Loading in data
09:32:29 Loaded VDJ data from Data.in

 Loading GEX failed
object 'directory_read10x' not found
 Getting VDJ GEX stats
Starting with 1 of 1
Getting 10x stats
09:32:32 Got VDJ GEX stats
`

Is there a way to circumvent either error, or to get the best of both worlds between CRAN and github versions?

Thanks!

**Comment by vickreiner** [comment]
Hi,
Thanks for noting this! 
We have pushed some new features and bugfixes which have not made it to CRAN yet.
We plan to push the next version to CRAN this week to sync it up.

Concerning the VDJ GEX matrix, I did push a fix, so that problem should now be solved in the Git install.

**Comment by EdGreen21** [comment]
can confirm that pulling latest version from github fixes this
