### ISSUE TITLE
antibody forests for sparse data

### ISSUE THREAD

**Issue by EdGreen21** [alexyermanos/Platypus#28]
I got Platypus using the devtools::install_github() command, and wanted to run Antibody forests on a sparse dataset from a autoimmune patient CSF sample:

```
AntibodyForests(VGM[[1]],
+                 network.algorithm = 'tree',
+                 specific.networks = 'clonotype1') %>% AntibodyForests_plot(node.label = NULL, node.scale.factor = 8) 
```
And received the error:

`Error in network.list[[i]] : subscript out of bounds`

In all liklihood this means that there were too few B cells (275) to make a network, but I thought I'd flag this here with the suggestion of the function failing more informatively

**Comment by tudorcotet** [comment]
Hi! Thank you for your feedback - the AntibodyForests functions are still under development and we are glad to receive advice on how to improve the,. We plan to include some more intuitive error messages in the next CRAN push!
