### ISSUE TITLE
CITE-Seq integration

### ISSUE THREAD

**Issue by sraju89** [alexyermanos/Platypus#29]
I see that you guys are planning on implementing feature barcodes for CITE-Seq-any idea when it might be ready?

I was also wondering if anyone has a suggestion of a workaround to incoporate CITE-seq data. 

Thanks

**Comment by vickreiner** [comment]
Hi!
Yes, the plan is to add this, but we have not gotten to it yet. Unfortunately, I cannot give you a target time. 
To work with Cite-seq, you can prepare a processed Seurat Object containing Cite-Seq information, which you can then use as `Seurat.in` input to the VDJ_GEX_matrix function. This will then generate the VGM object from your Seurat and cellranger VDJ output paths, while keeping Cite-seq data 

Hope that helps!
