### ISSUE TITLE
Help and idea

### ISSUE THREAD

**Issue by Mussa1122** [alexyermanos/Platypus#30]
Hi

I need your personal point of view please 

I have two `bulk RNA-seq` patients (PBMC) on which I run `mixcr`

For the same two patients I have `5' single cell` on which I run `TRUST4`

I am seeing more clones derived by `sc RNA-seq` and more clonality derived by `Bulk RNA-seq`

I named my bulk RNA-seq samples as TCR and my sc RNA-seq as TRUST

![Rplot02](https://user-images.githubusercontent.com/68249398/196688736-31ed214a-1921-4289-9580-6759aee9537d.png)
![Rplot07](https://user-images.githubusercontent.com/68249398/196688836-56639565-ab34-4031-9390-5b22c986e166.png)

Please, personally do you have any idea what could be an interpretation for this?

Thank you for any help

**Comment by vickreiner** [comment]
Hi!
I do not know the cause of this, but I can hypothesize given the experimental and computational methods:
1.	It would be helpful to assess input metrics for both experiments (cell count, viability, scRNA-seq chip saturation) and ultimately compare the number of cells that went into both experiments
2.	Similarly sequencing depth is different between the two methods, and you may find answers by comparing counts of common and rare transcripts.
3.	MiXCR and TRUST4 use different filtering and alignment algorithms. TRUST4 does claim to be more sensitive then MiXCR (I have not directly compared the two, but TRUST4s benchmarks are convincing to me) 
4.	Concerning analysis: how where the 4 repertoires clonotyped? I suggest you use a common clonotyping strategy (simplest would be same alpha and beta CDR3) to make the results comparable. 
Hope this helps! Please let us know if you find out the reasons behind this as that info would be interesting for the community.
