### ISSUE TITLE
Getting intuition

### ISSUE THREAD

**Issue by MaryGoAround** [alexyermanos/Platypus#32]
Hello team

I read in your vignette that `10x genomics cellranger returns some output from count for GEX (5' and 3') and VDJ for enriched immune receptor libraries` which could be visualized by Platypus, etc

So, having this, what is the purpose of tools like `mixcr` please? I mean, when 10x genomics cellranger gives these things why you use mixcr in a part of vignette?

Am I right mixcr and cellranger can do the same tasks?

Sorry I am very naive in immunology

Thanks for any help in advance

**Comment by vickreiner** [comment]
Hi,

I dont know if I have fully undestood the question. 
MiXCR is primarily an alignment tool and in Platypus we really only use it extract VDJ segment annotations (FR1, CDR1 etc.) and get a trimmed reference for each receptor. The capabilities of Mixcr go well beyond that and do overlap with other tools such as Cellranger as wells as Trust4
Hope this helps!
