### ISSUE TITLE
dummy VDJ

### ISSUE THREAD

**Issue by ChrisOmics** [alexyermanos/Platypus#33]
Hello, I am loving your tool thanks so much for developing. I do have a question.
 I have three samples. s1 s2 and s3 have GEX data, and s1 and s2 have VDJ. Is there a way to make a dummy VDJ so I can load them into a VDJ_GEX_matrix?

**Comment by vickreiner** [comment]
Hi Chris,

you can just ommit the VDJ.input.directory.list argument and run the function without VDJ:
`VDJ.out.directory.list <- list("~/VDJ/S1/", "~/VDJ/S2/")

VGM <- VDJ_GEX_matrix(
VDJ.out.directory.list = VDJ.out.directory.list,
... #other arguments applicable to GEX processing
)`

Thanks and let us know if you encounter any issues.
