### ISSUE TITLE
Assigning characteristics to samples in vgm 

### ISSUE THREAD

**Issue by zoqaiyum** [alexyermanos/Platypus#39]
Hi, 

I have successfully been able to use the VDJ_GEX_matrix function to create the vgm matrix that includes healthy control (HC) blood samples, patient blood samples, and patient tissue samples. Is there any way to assign characteristics to the vgm that specifies a certain sample is HC or patient? This way whenever creating UMAP plots of gene expression, it would be possible to only create UMAP of specific samples instead of using all samples in the matrix (for example, stratifying based on only HC vs patient blood or patient blood vs patient tissue).

Many thanks!

**Comment by tudorcotet** [comment]
Hi, 

Currently, there is no function to subset or transform the entire VGM object. We will add one in the next update! 

We recommend modifying the VGM[[1]] object as a typical data frame to add your new column specifying the sample origin, and doing the same for the VGM[[2]] object – which is a Seurat object. To do so, you can modify its metadata and add the aforementioned column – VGM[[2]]@meta.data.

Hope this solves your issue!
