### ISSUE TITLE
Issue loading VDJ data

### ISSUE THREAD

**Issue by leeanapeters** [alexyermanos/Platypus#6]
Hi there, I am really excited to use your package but am having issues using VDJ_GEX_matrix(), I am getting an error that loading the VDJ failed.  The folder paths contain the barcodes, features and matrix files for gex and filtered_contig_annotations.csv for vdj. These were generated via the regular cell ranger count pipeline followed by the aggr pipeline. Any help would be much appreciated!

GEX.out.directory.list <- list() ### Set directory to the outs folder of cellranger count
> GEX.out.directory.list[[1]] <- c("/Volumes/PATH$/SHARE/BRUSKO_LAB/SINGLE-CELL_DATA_ARCHIVE/NS2231/Aggregated 6528/filtered_feature_bc_matrix/")
> vgm <- VDJ_GEX_matrix(VDJ.out.directory.list = VDJ.out.directory.list,
+                       GEX.out.directory.list = GEX.out.directory.list,
+                       GEX.integrate = T,
+                       VDJ.combine = T,
+                       integrate.GEX.to.VDJ = T,
+                       integrate.VDJ.to.GEX = T, #This will adjunct the VDJ information as metadata to the GEX object
+                       exclude.GEX.not.in.VDJ = F,
+                       filter.overlapping.barcodes.GEX = T,
+                       filter.overlapping.barcodes.VDJ = T,
+                       get.VDJ.stats = T,
+                       parallel.processing = "none", #see note at the end of this chunk
+                       trim.and.align = F #Do not align BCR sequences to reference 
+                       )
Loading in data 

2021-10-25 11:32:09
Loading VDJ failed 

cannot open the connection

**Comment by alexyermanos** [comment]
It seems that there are multiple matrices/objects for the gene expression in the 6414_cellranger/outs/filtered_feature_bc_matrix directory based on the error message. can you paste the list of files located in this directory (e.g. "ls 6414_cellranger/outs/filtered_feature_bc_matrix")? is it just the normal output of cellranger count function?

**Comment by vickreiner** [comment]
Hi!
I am sorry for the late answer to this thread. 
The issue was most likely related to a wrong list assignment within the function. I just pushed a fix to this. 
Please source the function VDJ_GEX_matrix from the R directory directly until we update the build.

**Comment by leeanapeters** [comment]
Hi there,

I am getting a different error now, I think I sourced the function correctly (forgive me if not, I am an R novice) from https://github.com/alexyermanos/Platypus/blob/master/R/VDJ_GEX_matrix.R. 

This time it seems that both types of data are loaded, but here is where the function stops: 

Loading in data 

2021-12-02 17:09:54
Loaded VDJ data 

2021-12-02 17:10:12
10X data contains more than one type and is being returned as a list containing matrices of each type.
10X data contains more than one type and is being returned as a list containing matrices of each type.
10X data contains more than one type and is being returned as a list containing matrices of each type.
10X data contains more than one type and is being returned as a list containing matrices of each type.
GEX input 1 contains multiple count matrices. 
GEX input 1 element 1 contains > 100 features and will be loaded as GEX 
GEX input 1 element 2 contains < 100 features and will be loaded as FB 
Loaded GEX and FB data 

[1] "2021-12-02 17:11:59 EST"
Getting VDJ GEX stats 

Starting with 1 of 4...

Getting lookup tables... 

Starting with 2 of 4...

Getting lookup tables... 

Starting with 3 of 4...

Getting lookup tables... 

Starting with 4 of 4...

Getting lookup tables... 

Getting 10x stats 

Done with VDJ_GEX_stats 

Got VDJ GEX stats 

[1] "2021-12-02 17:12:04 EST"
For sample 1: 10851 cell assigned barcodes in GEX, 2113 cell assigned high confidence barcodes in VDJ. Overlap: 2079 

For sample 2: 9726 cell assigned barcodes in GEX, 2253 cell assigned high confidence barcodes in VDJ. Overlap: 2236 

For sample 3: 9726 cell assigned barcodes in GEX, 3729 cell assigned high confidence barcodes in VDJ. Overlap: 53 

For sample 4: 11423 cell assigned barcodes in GEX, 1575 cell assigned high confidence barcodes in VDJ. Overlap: 22 

 Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'unique': subscript out of bounds. 

Any help would be much appreciated.

Thanks!

**Comment by vickreiner** [comment]
Hi!
Thanks for the quick answer. Sorry that it still did not work. 
I tried replicating this error but was not able to so far. 
If possible could you try running the function just with your first GEX and VDJ input paths (just sample 1). 
If that still ends up with the same error, could you try running the function with filter.overlapping.barcodes.GEX = FALSE
Thanks!

**Comment by leeanapeters** [comment]
That actually worked fine for just the first sample!

**Comment by vickreiner** [comment]
Then I suppose there is an issue with the input files of sample 2 - 4. You can check if all have been run with the same cellranger version and within the same run. Did you provide Feature barcode / hashing barcode information to all or just to the first sample? 
Thanks again for trying it out!

**Comment by leeanapeters** [comment]
It seems like there is no issue when I run them individually, only when I try to run them as a list. They all have feature barcodes and were processed in the same run. Is there a way to make sure I can run them together or is there a way to merge the output?

**Comment by vickreiner** [comment]
Running all together should work. I will have a look back and let you know as soon as possible. 
In the meantime, running individually will work, but you would have to integrate the GEX Seurat objects in post. (See: https://satijalab.org/seurat/articles/integration_introduction.html)

**Comment by vickreiner** [comment]
Hi!
I made another attempt at fixing it. You can source the updated function and run the 4 samples again. https://github.com/alexyermanos/Platypus/blob/master/R/VDJ_GEX_matrix.R
Sorry for the delay
